name: autocomplete_textfield
description: A simple and versatile autocomplete text field for flutter, supporting multiple datatypes.
version: 1.7.3
author: Felix McCuaig <felixmccuaigdev@gmail.com>
homepage: https://github.com/felixlucien/flutter-autocomplete-textfield

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
      
flutter:
  uses-material-design: true